import sys
import os
import re
import shutil
import subprocess
import logging
import urllib.request
import urllib.error
from datetime import datetime
from urllib.parse import urlparse

from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QLineEdit, QPushButton, QPlainTextEdit, QFileDialog,
    QMessageBox, QCheckBox, QInputDialog, QDialog, QDialogButtonBox,
    QFrame, QSpinBox, QTabWidget, QTextEdit, QGroupBox, QFormLayout,
    QStatusBar, QComboBox, QProgressBar, QDesktopWidget, QListWidget,
    QListWidgetItem, QStackedWidget, QTextBrowser
)
from PyQt5.QtCore import Qt, QProcess, QTimer, pyqtSignal, QSettings, QThread
from PyQt5.QtGui import QFont, QTextCursor, QDesktopServices
from PyQt5.QtCore import QUrl

# ============================================================
# Cookie 一键下载工作线程
# ============================================================
class CookieDownloadWorker(QThread):
    log_signal = pyqtSignal(str)
    finished_signal = pyqtSignal(bool, str)

    def __init__(self, domain, output_dir, parent=None):
        super().__init__(parent)
        self.domain = domain
        self.output_dir = output_dir

    def run(self):
        try:
            self.log_signal.emit("正在检查/安装 browser_cookie3 ...")
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "browser_cookie3"],
                capture_output=True, check=True
            )

            import browser_cookie3

            self.log_signal.emit(f"正在从默认浏览器提取 {self.domain} 的 cookies ...")

            cookiejar = None
            browser_names = ["chrome", "firefox", "opera", "edge", "chromium", "brave"]
            for browser_name in browser_names:
                try:
                    load_func = getattr(browser_cookie3, browser_name, None)
                    if load_func is None:
                        continue
                    cookiejar = load_func(domain_name=self.domain)
                    if cookiejar and len(cookiejar) > 0:
                        self.log_signal.emit(f"成功从 {browser_name} 浏览器提取到 {len(cookiejar)} 个 cookies")
                        break
                except Exception:
                    continue

            if cookiejar is None or len(cookiejar) == 0:
                self.finished_signal.emit(False, f"未能从浏览器中提取到 {self.domain} 的 cookies。\n请确保您已在浏览器中登录该平台。")
                return

            os.makedirs(self.output_dir, exist_ok=True)
            output_path = os.path.join(self.output_dir, "cookies.txt")

            with open(output_path, "w", encoding="utf-8") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by You-Get/YT-DLP Batch Download Tool\n")
                f.write("# \n")
                for cookie in cookiejar:
                    domain = cookie.domain if cookie.domain else self.domain
                    flag = "TRUE" if domain.startswith(".") else "FALSE"
                    path = cookie.path if cookie.path else "/"
                    secure = "TRUE" if cookie.secure else "FALSE"
                    expires = str(int(cookie.expires)) if cookie.expires else "0"
                    name = cookie.name if cookie.name else ""
                    value = cookie.value if cookie.value else ""
                    f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")

            self.log_signal.emit(f"Cookies 已导出到: {output_path}")
            self.finished_signal.emit(True, output_path)

        except subprocess.CalledProcessError as e:
            self.finished_signal.emit(False, f"安装 browser_cookie3 失败: {e.stderr.decode() if e.stderr else str(e)}")
        except Exception as e:
            self.finished_signal.emit(False, f"导出 cookies 失败: {str(e)}")


# ============================================================
# 协议加载线程（在线请求）
# ============================================================
class AgreementLoadThread(QThread):
    """在后台线程请求在线协议内容，避免阻塞 UI。"""
    finished_signal = pyqtSignal(bool, str)  # (成功?, 内容或错误信息)

    def __init__(self, url, parent=None):
        super().__init__(parent)
        self.url = url

    def run(self):
        try:
            req = urllib.request.Request(
                self.url,
                headers={
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                                  "DownloadTool/1.0"
                }
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                html = resp.read().decode("utf-8", errors="replace")
            self.finished_signal.emit(True, html)
        except Exception as e:
            self.finished_signal.emit(False, str(e))


# ============================================================
# 用户协议对话框（在线加载，滚动到底部才能同意）
# ============================================================
class AgreementDialog(QDialog):
    # 供程序内 QTextBrowser 加载的内联样式版本
    EMBED_URL  = "https://tim-cn.github.io/download-tool/embed/terms.html"
    # 供用户点击"在浏览器中打开"用
    PUBLIC_URL = "https://tim-cn.github.io/download-tool/terms.html"

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("用户协议与使用条款")
        self.resize(760, 640)
        self.setModal(True)

        # 去掉标题栏 X，并禁用 ESC 关闭
        self.setWindowFlags(
            (self.windowFlags() | Qt.WindowTitleHint | Qt.WindowSystemMenuHint)
            & ~Qt.WindowCloseButtonHint
        )

        self._agreed = False
        self._no_ask_again = False
        self._has_reached_bottom = False
        self._load_thread = None

        self._init_ui()

        # 启动后立刻发起网络请求
        QTimer.singleShot(0, self._start_load)

    # ---------- UI ----------
    def _init_ui(self):
        outer = QVBoxLayout(self)
        outer.setContentsMargins(14, 14, 14, 14)

        self.stack = QStackedWidget()
        outer.addWidget(self.stack, 1)

        # 页 0：加载中
        self._loading_page = self._build_loading_page()
        self.stack.addWidget(self._loading_page)

        # 页 1：协议内容
        self._content_page = self._build_content_page()
        self.stack.addWidget(self._content_page)

        # 页 2：网络错误
        self._error_page = self._build_error_page()
        self.stack.addWidget(self._error_page)

    def _build_loading_page(self):
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.addStretch()
        label = QLabel("正在从服务器获取最新协议内容，请稍候…")
        label.setAlignment(Qt.AlignCenter)
        label.setStyleSheet("color: #555; font-size: 14px;")
        layout.addWidget(label)
        bar = QProgressBar()
        bar.setRange(0, 0)
        bar.setFixedWidth(280)
        h = QHBoxLayout()
        h.addStretch(); h.addWidget(bar); h.addStretch()
        layout.addLayout(h)
        layout.addStretch()
        return page

    def _build_content_page(self):
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(8)

        tip = QLabel(
            "请下拉阅读完整协议。只有当您滚动至协议底部后，下方的同意选项才会被激活。"
        )
        tip.setWordWrap(True)
        tip.setStyleSheet(
            "color: #444; padding: 8px 10px; background-color: #eef5ff; "
            "border: 1px solid #c8e1ff; border-radius: 4px; font-size: 12px;"
        )
        layout.addWidget(tip)

        # 顶部小工具行：在浏览器中打开
        tools_row = QHBoxLayout()
        tools_row.addStretch()
        open_in_browser_btn = QPushButton("在浏览器中打开完整版")
        open_in_browser_btn.setFlat(True)
        open_in_browser_btn.setStyleSheet("color: #0078d4; font-size: 12px;")
        open_in_browser_btn.setCursor(Qt.PointingHandCursor)
        open_in_browser_btn.clicked.connect(
            lambda: QDesktopServices.openUrl(QUrl(self.PUBLIC_URL))
        )
        tools_row.addWidget(open_in_browser_btn)
        layout.addLayout(tools_row)

        self.text_edit = QTextBrowser()
        self.text_edit.setOpenExternalLinks(True)
        self.text_edit.setReadOnly(True)
        self.text_edit.setStyleSheet(
            "QTextBrowser { background: #fbfbfb; border: 1px solid #ddd; "
            "border-radius: 4px; padding: 4px; }"
        )
        self.text_edit.verticalScrollBar().valueChanged.connect(self._on_scroll)
        layout.addWidget(self.text_edit, 1)

        self.agree_check = QCheckBox(
            "我已完整阅读、理解并同意本《用户协议与使用条款》的全部内容，并愿意遵守相关约定"
        )
        self.agree_check.setEnabled(False)
        self.agree_check.setStyleSheet("color: #999; font-size: 13px;")
        self.agree_check.stateChanged.connect(self._on_agree_toggle)
        layout.addWidget(self.agree_check)

        self.no_ask_check = QCheckBox("下次不再询问")
        self.no_ask_check.setStyleSheet("color: #555; font-size: 12px;")
        layout.addWidget(self.no_ask_check)

        btn_row = QHBoxLayout()
        btn_row.addStretch()
        self.enter_btn = QPushButton("进入程序")
        self.enter_btn.setEnabled(False)
        self.enter_btn.setMinimumWidth(130)
        self.enter_btn.setMinimumHeight(32)
        self.enter_btn.clicked.connect(self._on_enter)
        btn_row.addWidget(self.enter_btn)
        layout.addLayout(btn_row)

        return page

    def _build_error_page(self):
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.addStretch()

        icon = QLabel("⚠")
        icon.setAlignment(Qt.AlignCenter)
        icon.setStyleSheet("font-size: 42px; color: #d32f2f;")
        layout.addWidget(icon)

        msg = QLabel(
            "<div style='font-size:14px;color:#333;text-align:center;'>"
            "<b>本应用需要连接互联网使用</b><br><br>"
            "无法获取在线用户协议内容，请检查网络连接后重试。"
            "</div>"
        )
        msg.setAlignment(Qt.AlignCenter)
        msg.setWordWrap(True)
        layout.addWidget(msg)

        self.error_detail_label = QLabel("")
        self.error_detail_label.setAlignment(Qt.AlignCenter)
        self.error_detail_label.setWordWrap(True)
        self.error_detail_label.setStyleSheet("color: #888; font-size: 12px;")
        layout.addWidget(self.error_detail_label)

        layout.addSpacing(16)

        btn_row = QHBoxLayout()
        btn_row.addStretch()

        retry_btn = QPushButton("重新连接")
        retry_btn.setMinimumWidth(120)
        retry_btn.setMinimumHeight(32)
        retry_btn.clicked.connect(self._start_load)
        btn_row.addWidget(retry_btn)

        exit_btn = QPushButton("退出应用")
        exit_btn.setMinimumWidth(120)
        exit_btn.setMinimumHeight(32)
        exit_btn.clicked.connect(self._on_exit_app)
        btn_row.addWidget(exit_btn)

        btn_row.addStretch()
        layout.addLayout(btn_row)

        layout.addStretch()
        return page

    # ---------- 加载逻辑 ----------
    def _start_load(self):
        # 切换到加载页
        self.stack.setCurrentWidget(self._loading_page)

        # 若已有线程在跑，先清理
        if self._load_thread is not None and self._load_thread.isRunning():
            return

        self._load_thread = AgreementLoadThread(self.EMBED_URL, self)
        self._load_thread.finished_signal.connect(self._on_load_finished)
        self._load_thread.start()

    def _on_load_finished(self, success, payload):
        if success:
            self._show_content(payload)
        else:
            self._show_error(payload)

    def _show_content(self, html):
        self.text_edit.setHtml(html)
        # 重置滚动与解锁状态
        self._has_reached_bottom = False
        self.agree_check.setChecked(False)
        self.agree_check.setEnabled(False)
        self.agree_check.setStyleSheet("color: #999; font-size: 13px;")
        self.enter_btn.setEnabled(False)

        self.stack.setCurrentWidget(self._content_page)

        # 内容短于可视区域时（无滚动条），直接解锁
        QTimer.singleShot(250, self._check_if_content_short)

    def _show_error(self, detail):
        self.error_detail_label.setText(f"错误详情：{detail}")
        self.stack.setCurrentWidget(self._error_page)

    def _on_exit_app(self):
        QApplication.quit()

    # ---------- 滚动解锁 ----------
    def _on_scroll(self, value):
        if self._has_reached_bottom:
            return
        bar = self.text_edit.verticalScrollBar()
        if bar.value() >= bar.maximum() - 5:
            self._has_reached_bottom = True
            self.agree_check.setEnabled(True)
            self.agree_check.setStyleSheet(
                "color: #1f2328; font-size: 13px; font-weight: 600;"
            )

    def _check_if_content_short(self):
        bar = self.text_edit.verticalScrollBar()
        if bar.maximum() == 0:
            self._has_reached_bottom = True
            self.agree_check.setEnabled(True)
            self.agree_check.setStyleSheet(
                "color: #1f2328; font-size: 13px; font-weight: 600;"
            )

    def _on_agree_toggle(self, state):
        self.enter_btn.setEnabled(self.agree_check.isChecked())

    def _on_enter(self):
        if not self.agree_check.isChecked():
            return
        self._agreed = True
        self._no_ask_again = self.no_ask_check.isChecked()
        self.accept()

    # ---------- 屏蔽关闭 ----------
    def keyPressEvent(self, event):
        if event.key() == Qt.Key_Escape:
            return
        super().keyPressEvent(event)

    def closeEvent(self, event):
        if self._agreed:
            event.accept()
        else:
            event.ignore()

    @property
    def agreed(self):
        return self._agreed

    @property
    def no_ask_again(self):
        return self._no_ask_again

# ============================================================
# 平台 Cookie 管理对话框
# ============================================================
class PlatformCookieManager(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.parent_widget = parent
        self.setWindowTitle("平台 Cookie 管理")
        self.resize(600, 400)

        # 存储 Cookie 的目录 (AppData/you-get batch download tool/cookies)
        appdata_dir = os.path.join(os.getenv("APPDATA", os.path.expanduser("~")),
                                    "you-get batch download tool")
        self.cookies_storage_dir = os.path.join(appdata_dir, "cookies")
        os.makedirs(self.cookies_storage_dir, exist_ok=True)

        # 预定义平台列表（域名 -> 显示名称）
        self.platforms = self._get_platform_list()

        layout = QVBoxLayout(self)

        # 说明标签
        info_label = QLabel("在此管理各视频平台的 Cookie 文件。程序将根据下载链接自动匹配对应平台的 Cookie。")
        info_label.setWordWrap(True)
        info_label.setStyleSheet("color: #666; margin-bottom: 8px;")
        layout.addWidget(info_label)

        # 列表显示已有 Cookie
        self.cookie_list = QListWidget()
        self.cookie_list.setAlternatingRowColors(True)
        layout.addWidget(self.cookie_list)

        # 按钮区域
        btn_layout = QHBoxLayout()
        add_btn = QPushButton("➕ 添加 Cookie")
        add_btn.clicked.connect(self.add_cookie)
        delete_btn = QPushButton("🗑 删除选中")
        delete_btn.clicked.connect(self.delete_cookie)
        open_folder_btn = QPushButton("📁 打开存储文件夹")
        open_folder_btn.clicked.connect(self.open_storage_folder)
        btn_layout.addWidget(add_btn)
        btn_layout.addWidget(delete_btn)
        btn_layout.addWidget(open_folder_btn)
        btn_layout.addStretch()
        layout.addLayout(btn_layout)

        # 确认关闭按钮
        button_box = QDialogButtonBox(QDialogButtonBox.Close)
        button_box.rejected.connect(self.accept)
        layout.addWidget(button_box)

        self.refresh_list()

    def _get_platform_list(self):
        """返回 (显示名称, 域名) 列表，用于添加时快速选择"""
        return [
            ("请选择", ""),
            ("哔哩哔哩 (bilibili.com)", "bilibili.com"),
            ("YouTube (youtube.com)", "youtube.com"),
            ("抖音国际版 (tiktok.com)", "tiktok.com"),
            ("网易云音乐 (music.163.com)", "music.163.com"),
            ("QQ音乐 (y.qq.com)", "y.qq.com"),
            ("优酷 (youku.com)", "youku.com"),
            ("腾讯视频 (v.qq.com)", "v.qq.com"),
            ("爱奇艺 (iqiyi.com)", "iqiyi.com"),
            ("抖音 (douyin.com)", "douyin.com"),
            ("快手 (kuaishou.com)", "kuaishou.com"),
            ("西瓜视频 (ixigua.com)", "ixigua.com"),
            ("微博 (weibo.com)", "weibo.com"),
            ("知乎 (zhihu.com)", "zhihu.com"),
            ("微博国际版 (weibo.intl)", "weibo.intl"),
            ("Twitter (twitter.com)", "twitter.com"),
            ("Facebook (facebook.com)", "facebook.com"),
            ("Instagram (instagram.com)", "instagram.com"),
            ("Twitch (twitch.tv)", "twitch.tv"),
            ("Reddit (reddit.com)", "reddit.com"),
            ("Pinterest (pinterest.com)", "pinterest.com"),
            ("VK (vk.com)", "vk.com"),
            ("Vimeo (vimeo.com)", "vimeo.com"),
            ("Dailymotion (dailymotion.com)", "dailymotion.com"),
            ("SoundCloud (soundcloud.com)", "soundcloud.com"),
            ("Spotify (spotify.com)", "spotify.com"),
            ("Tumblr (tumblr.com)", "tumblr.com"),
            ("Vine (vine.co)", "vine.co"),
            ("Periscope (periscope.tv)", "periscope.tv"),
            ("Vidme (vid.me)", "vid.me"),
            ("其他 (手动输入)", "")
        ]

    def refresh_list(self):
        """刷新列表，显示 cookies_storage_dir 下所有 .txt 文件"""
        self.cookie_list.clear()
        if not os.path.exists(self.cookies_storage_dir):
            return
        for filename in os.listdir(self.cookies_storage_dir):
            if filename.endswith(".txt"):
                filepath = os.path.join(self.cookies_storage_dir, filename)
                domain = filename[:-4]  # 去掉 .txt
                size = os.path.getsize(filepath)
                item_text = f"{domain}  ({size} 字节)"
                item = QListWidgetItem(item_text)
                item.setData(Qt.UserRole, filepath)   # 存储完整路径
                self.cookie_list.addItem(item)

    def add_cookie(self):
        """导入新的 Cookie 文件"""
        # 选择 cookie 文件
        file_path, _ = QFileDialog.getOpenFileName(
            self, "选择 Cookie 文件", "", "文本文件 (*.txt);;所有文件 (*)"
        )
        if not file_path:
            return

        # 获取平台域名
        dialog = QDialog(self)
        dialog.setWindowTitle("选择平台")
        dialog.resize(400, 200)
        dlg_layout = QVBoxLayout(dialog)

        dlg_layout.addWidget(QLabel("请选择或输入平台域名 (例如 bilibili.com)："))

        combo = QComboBox()
        for display_name, domain in self.platforms:
            combo.addItem(display_name, domain)
        dlg_layout.addWidget(combo)

        manual_edit = QLineEdit()
        manual_edit.setPlaceholderText("或手动输入域名 (如 www.example.com)")
        dlg_layout.addWidget(manual_edit)

        def on_combo_changed(index):
            domain = combo.itemData(index)
            if domain and domain != "":
                manual_edit.setText(domain)
        combo.currentIndexChanged.connect(on_combo_changed)

        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttons.accepted.connect(dialog.accept)
        buttons.rejected.connect(dialog.reject)
        dlg_layout.addWidget(buttons)

        if dialog.exec_() != QDialog.Accepted:
            return

        domain = manual_edit.text().strip()
        if not domain:
            QMessageBox.warning(self, "错误", "平台域名不能为空")
            return

        # 规范域名：去除 http:// 等前缀，去除末尾斜杠
        domain = domain.lower().replace("http://", "").replace("https://", "").split("/")[0]

        # 目标文件名
        target_filename = f"{domain}.txt"
        target_path = os.path.join(self.cookies_storage_dir, target_filename)

        # 如果文件已存在，询问是否覆盖
        if os.path.exists(target_path):
            reply = QMessageBox.question(
                self, "文件已存在",
                f"平台 {domain} 的 Cookie 文件已存在，是否覆盖？",
                QMessageBox.Yes | QMessageBox.No
            )
            if reply != QMessageBox.Yes:
                return

        # 复制文件
        try:
            shutil.copy2(file_path, target_path)
            self.refresh_list()
            QMessageBox.information(self, "成功", f"Cookie 已添加至平台：{domain}")
            # 通知主窗口刷新状态
            if self.parent_widget:
                self.parent_widget.on_cookie_changed()
        except Exception as e:
            QMessageBox.critical(self, "错误", f"复制文件失败：{e}")

    def delete_cookie(self):
        """删除选中的 Cookie"""
        current = self.cookie_list.currentItem()
        if not current:
            QMessageBox.information(self, "提示", "请先选中要删除的项目")
            return
        filepath = current.data(Qt.UserRole)
        domain = os.path.basename(filepath)[:-4]
        reply = QMessageBox.question(
            self, "确认删除",
            f"确定要删除平台 {domain} 的 Cookie 吗？",
            QMessageBox.Yes | QMessageBox.No
        )
        if reply == QMessageBox.Yes:
            try:
                os.remove(filepath)
                self.refresh_list()
                if self.parent_widget:
                    self.parent_widget.on_cookie_changed()
            except Exception as e:
                QMessageBox.critical(self, "错误", f"删除失败：{e}")

    def open_storage_folder(self):
        """打开存储文件夹"""
        os.startfile(self.cookies_storage_dir)


# ============================================================
# 设置对话框（集成工具选择和多平台 Cookie 管理入口）
# ============================================================
class SettingsDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("设置")
        self.resize(700, 500)
        self.parent_widget = parent
        self.settings = QSettings("YouGetBatchTool", "Settings")

        layout = QVBoxLayout(self)

        # 创建标签页
        tabs = QTabWidget()
        layout.addWidget(tabs)

        # ---- 通用设置标签页 ----
        general_tab = QWidget()
        general_layout = QVBoxLayout(general_tab)

        # 日志目录
        log_layout = QHBoxLayout()
        log_layout.addWidget(QLabel("日志目录:"))
        self.log_dir_edit = QLineEdit()
        log_layout.addWidget(self.log_dir_edit)
        log_browse_btn = QPushButton("浏览...")
        log_browse_btn.clicked.connect(self.browse_log_dir)
        log_layout.addWidget(log_browse_btn)
        log_open_btn = QPushButton("打开")
        log_open_btn.clicked.connect(self.open_log_dir)
        log_layout.addWidget(log_open_btn)
        
        # ===== 新增：移动按钮 =====
        log_move_btn = QPushButton("移动")
        log_move_btn.clicked.connect(self.move_log_dir)
        log_layout.addWidget(log_move_btn)
        # ========================
        
        general_layout.addLayout(log_layout)

        # 下载工具选择
        tool_layout = QHBoxLayout()
        tool_layout.addWidget(QLabel("下载引擎:"))
        self.tool_combo = QComboBox()
        self.tool_combo.addItem("you-get (适合国内视频站、B站、优酷等)", "you-get")
        self.tool_combo.addItem("yt-dlp (功能更强大，适合YouTube、国外站、支持更多格式)", "yt-dlp")
        self.tool_combo.setToolTip(
            "you-get: 对国内网站支持较好，操作简单\n"
            "yt-dlp: 基于youtube-dl，支持上千网站，更新频繁，推荐用于YouTube及国外站点"
        )
        tool_layout.addWidget(self.tool_combo)

        # 添加一个帮助按钮显示详细区别
        tool_help_btn = QPushButton("❓")
        tool_help_btn.setFixedSize(24, 24)
        tool_help_btn.setToolTip("查看详细区别")
        tool_help_btn.clicked.connect(self.show_tool_help)
        tool_layout.addWidget(tool_help_btn)
        tool_layout.addStretch()
        general_layout.addLayout(tool_layout)


        # 自定义请求头
        header_group = QGroupBox("自定义请求头 (每行一个，格式: Key: Value)")
        header_layout = QVBoxLayout(header_group)
        hint = QLabel(
            "智能匹配规则：\n"
            "• 值中含域名的请求头（如 Referer: https://www.example.com/）只对该域名的链接生效。\n"
            "• 值中不含域名的请求头（如 User-Agent、Accept）对所有链接全局生效。"
        )
        hint.setWordWrap(True)
        hint.setStyleSheet("color: #666; font-size: 11px;")
        header_layout.addWidget(hint)
        self.header_edit = QPlainTextEdit()
        self.header_edit.setPlaceholderText(
            "示例：\n"
            "Referer: https://www.example.com/\n"
            "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) ..."
        )
        self.header_edit.setMaximumHeight(100)
        header_layout.addWidget(self.header_edit)
        general_layout.addWidget(header_group)

        general_layout.addStretch()
        tabs.addTab(general_tab, "通用")

        # ---- Cookie 管理标签页 ----
        cookie_tab = QWidget()
        cookie_layout = QVBoxLayout(cookie_tab)

        # 说明
        cookie_info = QLabel(
            "您可以在此为不同平台分别添加 Cookie，下载时程序会自动匹配。\n"
            "对于需要登录才能下载或获取高清视频的网站，请添加有效的 Cookie。"
        )
        cookie_info.setWordWrap(True)
        cookie_layout.addWidget(cookie_info)

        # 添加一个按钮打开 Cookie 管理对话框
        manage_cookie_btn = QPushButton("打开平台 Cookie 管理器")
        manage_cookie_btn.clicked.connect(self.open_cookie_manager)
        cookie_layout.addWidget(manage_cookie_btn)

        # 一键下载 Cookie 区域（快捷方式）
        oneclick_group = QGroupBox("一键下载 Cookie (从浏览器导出)")
        oneclick_layout = QVBoxLayout(oneclick_group)
        hint = QLabel("如果不知道如何获取 Cookie，可以使用此功能从您的浏览器中自动提取。")
        hint.setWordWrap(True)
        oneclick_layout.addWidget(hint)

        platform_select_layout = QHBoxLayout()
        platform_select_layout.addWidget(QLabel("选择平台:"))
        self.quick_platform_combo = QComboBox()
        # 填充常用平台（用于一键下载）
        common_platforms = [
            ("哔哩哔哩", "bilibili.com"),
            ("YouTube", "youtube.com"),
            ("优酷", "youku.com"),
            ("腾讯视频", "v.qq.com"),
            ("爱奇艺", "iqiyi.com"),
            ("抖音", "douyin.com"),
            ("快手", "kuaishou.com"),
            ("Twitter", "twitter.com"),
        ]
        for name, domain in common_platforms:
            self.quick_platform_combo.addItem(name, domain)
        platform_select_layout.addWidget(self.quick_platform_combo)
        platform_select_layout.addStretch()
        oneclick_layout.addLayout(platform_select_layout)

        quick_download_btn = QPushButton("一键导出 Cookie 并自动添加")
        quick_download_btn.clicked.connect(self.one_click_download_cookie)
        oneclick_layout.addWidget(quick_download_btn)

        cookie_layout.addWidget(oneclick_group)
        cookie_layout.addStretch()
        tabs.addTab(cookie_tab, "Cookie 管理")

        # 对话框按钮
        button_box = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        button_box.accepted.connect(self.save_settings)
        button_box.rejected.connect(self.reject)

        # ===== 底部链接行 =====
        FAQ_URL   = "https://tim-cn.github.io/download-tool/faq.html"
        TERMS_URL = "https://tim-cn.github.io/download-tool/terms.html"

        footer_row = QHBoxLayout()

        faq_link = QPushButton("答疑解惑")
        faq_link.setFlat(True)
        faq_link.setStyleSheet("color: #0078d4; text-align: left; border: none;")
        faq_link.setCursor(Qt.PointingHandCursor)
        faq_link.clicked.connect(lambda: QDesktopServices.openUrl(QUrl(FAQ_URL)))

        terms_link = QPushButton("用户协议")
        terms_link.setFlat(True)
        terms_link.setStyleSheet("color: #0078d4; text-align: left; border: none;")
        terms_link.setCursor(Qt.PointingHandCursor)
        terms_link.clicked.connect(lambda: QDesktopServices.openUrl(QUrl(TERMS_URL)))

        footer_row.addWidget(faq_link)
        footer_row.addWidget(terms_link)
        footer_row.addStretch()
        footer_row.addWidget(button_box)
        layout.addLayout(footer_row)
        # ==============================

        self.load_settings()

    def show_tool_help(self):
        """显示两种工具的详细区别"""
        msg = QMessageBox(self)
        msg.setWindowTitle("下载引擎帮助")
        msg.setText(
            "<b>you-get</b><br>"
            "- 特点：轻量、简单，对国内视频网站（B站、优酷、腾讯等）支持很好。<br>"
            "- 优点：无需复杂配置，直接下载。<br>"
            "- 缺点：支持的网站相对较少，更新不如yt-dlp频繁。<br><br>"
            "<b>yt-dlp</b><br>"
            "- 特点：基于youtube-dl，功能极其强大，支持超过1000个网站。<br>"
            "- 优点：支持提取字幕、播放列表、格式选择丰富，更新活跃，适合YouTube及国外站点。<br>"
            "- 缺点：某些国内网站可能需要额外配置或Cookie。<br><br>"
            "<b>推荐使用场景</b><br>"
            "• 主要下载B站、优酷、腾讯等国内视频 → 选择 you-get<br>"
            "• 主要下载YouTube、Twitter、国外网站或需要高级功能 → 选择 yt-dlp<br>"
            "• 不确定时可以两者都安装，根据下载链接灵活切换。<br><br>"
            "提示：两个工具可以同时安装，本程序会根据您的选择调用对应的命令行。"
        )
        msg.exec_()

    def open_cookie_manager(self):
        """打开平台 Cookie 管理器"""
        dlg = PlatformCookieManager(self.parent_widget)
        dlg.exec_()

    def one_click_download_cookie(self):
        """一键下载 Cookie 并自动添加到管理器"""
        domain = self.quick_platform_combo.currentData()
        platform_name = self.quick_platform_combo.currentText()
        if not domain:
            QMessageBox.warning(self, "提示", "请选择有效的平台")
            return

        # 确认登录对话框
        confirm_dialog = QDialog(self)
        confirm_dialog.setWindowTitle("登录确认")
        confirm_dialog.resize(500, 200)
        cf_layout = QVBoxLayout(confirm_dialog)

        cf_layout.addWidget(QLabel(
            f"<p style='color:red; font-weight:bold;'>"
            f"请确认您已经在默认浏览器中登录了「{platform_name}」({domain})，然后继续。</p>"
        ))

        # 倒计时
        countdown_label = QLabel("5s")
        countdown_label.setAlignment(Qt.AlignCenter)
        countdown_label.setStyleSheet("font-size: 24px; font-weight: bold; color: #d32f2f;")
        cf_layout.addWidget(countdown_label)

        btn_box = QDialogButtonBox()
        ok_btn = btn_box.addButton("确定", QDialogButtonBox.AcceptRole)
        ok_btn.setEnabled(False)
        cancel_btn = btn_box.addButton("取消", QDialogButtonBox.RejectRole)
        btn_box.rejected.connect(confirm_dialog.reject)
        btn_box.accepted.connect(confirm_dialog.accept)
        cf_layout.addWidget(btn_box)

        # 倒计时逻辑
        countdown_value = 5
        timer = QTimer(confirm_dialog)

        def update_countdown():
            nonlocal countdown_value
            countdown_value -= 1
            if countdown_value <= 0:
                timer.stop()
                countdown_label.setText("")
                countdown_label.setVisible(False)
                ok_btn.setEnabled(True)
            else:
                countdown_label.setText(f"{countdown_value}s")
        timer.timeout.connect(update_countdown)
        timer.start(1000)

        if confirm_dialog.exec_() != QDialog.Accepted:
            timer.stop()
            return

        timer.stop()

        # 后台导出
        download_dir = os.path.join(os.path.expanduser("~"), "Downloads", "you-get batch download tool")
        os.makedirs(download_dir, exist_ok=True)

        progress_dialog = QDialog(self)
        progress_dialog.setWindowTitle("正在导出 Cookie")
        progress_dialog.resize(450, 150)
        pg_layout = QVBoxLayout(progress_dialog)
        progress_label = QLabel("正在从浏览器中提取 Cookie，请稍候...")
        pg_layout.addWidget(progress_label)
        progress_bar = QProgressBar()
        progress_bar.setRange(0, 0)
        pg_layout.addWidget(progress_bar)
        progress_dialog.setModal(True)
        progress_dialog.show()

        self.cookie_worker = CookieDownloadWorker(domain, download_dir)
        self.cookie_worker.log_signal.connect(lambda msg: progress_label.setText(msg))

        def on_finished(success, result):
            progress_dialog.close()
            if success:
                # 将导出的 cookie 添加到管理器
                appdata_dir = os.path.join(os.getenv("APPDATA", os.path.expanduser("~")),
                                            "you-get batch download tool")
                cookies_dir = os.path.join(appdata_dir, "cookies")
                os.makedirs(cookies_dir, exist_ok=True)
                target_path = os.path.join(cookies_dir, f"{domain}.txt")
                shutil.copy2(result, target_path)
                QMessageBox.information(self, "成功",
                                        f"Cookie 已成功导出并添加到平台「{platform_name}」\n"
                                        f"存储路径：{target_path}")
                if self.parent_widget:
                    self.parent_widget.on_cookie_changed()
            else:
                QMessageBox.warning(self, "失败", f"导出 Cookie 失败：\n{result}\n\n"
                                                "请确保：\n"
                                                "1. 已在浏览器中登录该平台\n"
                                                "2. 使用的浏览器为 Chrome、Firefox、Edge 等主流浏览器")

        self.cookie_worker.finished_signal.connect(on_finished)
        self.cookie_worker.start()

    def load_settings(self):
        default_log_dir = os.path.join(os.getenv("APPDATA", os.path.expanduser("~")),
                                       "you-get batch download tool")
        self.log_dir_edit.setText(self.settings.value("log_dir", default_log_dir))

        # 加载下载工具选择
        tool = self.settings.value("download_tool", "you-get")
        index = self.tool_combo.findData(tool)
        if index >= 0:
            self.tool_combo.setCurrentIndex(index)
        
        # 加载自定义请求头
        self.header_edit.setPlainText(self.settings.value("custom_headers", ""))

    def save_settings(self):
        new_log_dir = self.log_dir_edit.text().strip()
        self.settings.setValue("log_dir", new_log_dir)
        self.settings.setValue("download_tool", self.tool_combo.currentData())

        # 保存自定义请求头
        self.settings.setValue("custom_headers", self.header_edit.toPlainText().strip())

        self.accept()

        # 通知主窗口刷新
        if self.parent_widget:
            self.parent_widget.on_settings_changed()

    def browse_log_dir(self):
        path = QFileDialog.getExistingDirectory(self, "选择日志保存目录")
        if path:
            self.log_dir_edit.setText(path)

    def open_log_dir(self):
        path = self.log_dir_edit.text().strip()
        if path:
            os.startfile(path)

    def move_log_dir(self):
        """将现有日志目录下的所有内容移动到新目录"""
        old_dir = self.log_dir_edit.text().strip()
        if not old_dir or not os.path.exists(old_dir):
            QMessageBox.warning(self, "警告", "当前日志目录不存在或为空。")
            return

        new_parent_dir = QFileDialog.getExistingDirectory(self, "选择新的日志目录位置")
        if not new_parent_dir:
            return

        if os.path.normpath(old_dir) == os.path.normpath(new_parent_dir):
            QMessageBox.information(self, "提示", "新目录与当前目录相同，无需移动。")
            return

        reply = QMessageBox.question(
            self, "确认移动",
            f"确定要将当前日志目录下的所有文件移动到：\n{new_parent_dir}\n吗？",
            QMessageBox.Yes | QMessageBox.No
        )
        if reply != QMessageBox.Yes:
            return

        try:
            for item in os.listdir(old_dir):
                src = os.path.join(old_dir, item)
                dst = os.path.join(new_parent_dir, item)
                if os.path.exists(dst):
                    continue
                shutil.move(src, dst)

            # ===== 修复：主动持久化新路径 =====
            self.log_dir_edit.setText(new_parent_dir)
            self.settings.setValue("log_dir", new_parent_dir)  # 写入硬盘
            if self.parent_widget:
                self.parent_widget.on_settings_changed()       # 通知主窗口刷新 self.log_dir
            # ===================================

            QMessageBox.information(self, "成功", f"日志文件已成功移动至：\n{new_parent_dir}")
        except Exception as e:
            QMessageBox.critical(self, "错误", f"移动失败：{e}")


# ============================================================
# 安装引导窗口（修改为内置引擎指引）
# ============================================================
class InstallToolDialog(QDialog):
    def __init__(self, tool_name, parent=None):
        super().__init__(parent)
        self.tool_name = tool_name
        self.setWindowTitle(f"获取 {tool_name} 引擎")
        self.resize(600, 400)
        layout = QVBoxLayout(self)

        info_label = QLabel(
            f"本程序支持内置引擎，请将 <b>{tool_name}</b> 可执行文件放入程序目录下的「engines」文件夹。\n"
            f"您也可以从官方网站下载："
        )
        info_label.setWordWrap(True)
        layout.addWidget(info_label)

        # 下载链接
        if tool_name == "you-get":
            link = QLabel("<a href='https://github.com/soimort/you-get/releases'>https://github.com/soimort/you-get/releases</a>")
            link.setOpenExternalLinks(True)
            layout.addWidget(link)
            tip = QLabel("对于 Windows，请下载 you-get.exe；Linux/macOS 下载 you-get 可执行文件并赋予执行权限。")
        else:
            link = QLabel("<a href='https://github.com/yt-dlp/yt-dlp/releases'>https://github.com/yt-dlp/yt-dlp/releases</a>")
            link.setOpenExternalLinks(True)
            layout.addWidget(link)
            tip = QLabel("对于 Windows，请下载 yt-dlp.exe；Linux/macOS 下载 yt-dlp 可执行文件并赋予执行权限。\n"
                         "yt-dlp 需要 FFmpeg 合并视频音频，建议一并安装 FFmpeg。")
        tip.setWordWrap(True)
        layout.addWidget(tip)

        # 显示内置引擎目录路径
        engines_dir = self.get_engines_dir()
        path_label = QLabel(f"引擎文件夹路径：<b>{engines_dir}</b>")
        path_label.setWordWrap(True)
        layout.addWidget(path_label)

        open_folder_btn = QPushButton("打开引擎文件夹")
        open_folder_btn.clicked.connect(lambda: os.startfile(engines_dir))
        layout.addWidget(open_folder_btn)

        close_btn = QPushButton("关闭")
        close_btn.clicked.connect(self.close)
        layout.addWidget(close_btn)

    def get_engines_dir(self):
        # 与主窗口保持一致的引擎目录获取逻辑
        if getattr(sys, 'frozen', False):
            base_dir = sys._MEIPASS
        else:
            base_dir = os.path.dirname(os.path.abspath(__file__))
        engines_dir = os.path.join(base_dir, "engines")
        return engines_dir




# ============================================================
# 主窗口（支持工具切换和多平台 Cookie，内置引擎优先）
# ============================================================
class YouGetBatchDownloader(QMainWindow):
    log_signal = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.setWindowTitle("You-Get / YT-DLP 批量下载工具 By Tim-CN")
        self.setGeometry(100, 100, 950, 750)

        # 获取引擎目录（支持 PyInstaller 打包后的路径）
        if getattr(sys, 'frozen', False):
            # 打包后的 exe 中，引擎文件应放在 exe 同级的 engines 目录（或使用 --add-data 放到 sys._MEIPASS）
            # 为了灵活性，优先检查 exe 同级目录的 engines，再检查 sys._MEIPASS/engines
            exe_dir = os.path.dirname(sys.executable)
            self.engines_dir = os.path.join(exe_dir, "engines")
            if not os.path.isdir(self.engines_dir):
                # 回退到打包内部资源（如果使用 --add-data 将引擎打包进去）
                self.engines_dir = os.path.join(sys._MEIPASS, "engines")
        else:
            self.engines_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "engines")
        # 确保引擎目录存在
        os.makedirs(self.engines_dir, exist_ok=True)

        self.settings = QSettings("YouGetBatchTool", "Settings")
        self.log_dir = self.settings.value("log_dir", "")
        if not self.log_dir:
            self.log_dir = os.path.join(os.getenv("APPDATA", os.path.expanduser("~")),
                                        "you-get batch download tool")
        # 当前选中的下载工具
        self.current_tool = self.settings.value("download_tool", "you-get")
        # 检查工具可用性（记录路径）
        self.youget_available, self.youget_path = self.check_tool("you-get")
        self.ytdlp_available, self.ytdlp_path = self.check_tool("yt-dlp")

        self.max_parallel = 5
        self.processes = []
        self.url_queue = []
        self.total_tasks = 0
        self.success_count = 0
        self.fail_count = 0
        self.task_running = False
        self.stop_flag = False

        # Cookie 存储目录
        appdata_dir = os.path.join(os.getenv("APPDATA", os.path.expanduser("~")),
                                   "you-get batch download tool")
        self.cookies_storage_dir = os.path.join(appdata_dir, "cookies")
        os.makedirs(self.cookies_storage_dir, exist_ok=True)

        # 确保目录存在
        os.makedirs(appdata_dir, exist_ok=True)
        default_download_dir = os.path.join(os.path.expanduser("~"), "Downloads",
                                            "you-get batch download tool")
        os.makedirs(default_download_dir, exist_ok=True)

        saved_download_dir = self.settings.value("download_dir", "")
        if saved_download_dir and os.path.isdir(saved_download_dir):
            self.download_dir = saved_download_dir
        else:
            self.download_dir = default_download_dir
            self.settings.setValue("download_dir", self.download_dir)

        self.init_ui()
        self.log_signal.connect(self.append_log)

        if not os.path.exists(self.log_dir):
            os.makedirs(self.log_dir, exist_ok=True)

        self.update_tool_status()
        self.update_cookie_reminder()

    def init_ui(self):
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        layout = QVBoxLayout(central_widget)

        # ===== 第1行：设置、工具状态、工具切换 =====
        top_row = QHBoxLayout()
        settings_btn = QPushButton("⚙ 设置")
        settings_btn.clicked.connect(self.open_settings)
        top_row.addWidget(settings_btn)

        # 工具状态显示
        self.tool_status_label = QLabel()
        self.tool_status_label.setStyleSheet("padding: 2px 6px; border-radius: 3px;")
        top_row.addWidget(self.tool_status_label)

        # 快速切换工具下拉框
        top_row.addWidget(QLabel("切换引擎:"))
        self.tool_switch_combo = QComboBox()
        self.tool_switch_combo.addItem("you-get", "you-get")
        self.tool_switch_combo.addItem("yt-dlp", "yt-dlp")
        self.tool_switch_combo.setCurrentIndex(0 if self.current_tool == "you-get" else 1)
        self.tool_switch_combo.currentIndexChanged.connect(self.on_tool_switch)
        top_row.addWidget(self.tool_switch_combo)

        top_row.addStretch()

        # ===== 帮助与协议入口 =====
        HELP_URL  = "https://tim-cn.github.io/download-tool/faq.html"
        TERMS_URL = "https://tim-cn.github.io/download-tool/terms.html"

        help_btn = QPushButton("❓ 帮助")
        help_btn.setToolTip("打开在线帮助与常见问题")
        help_btn.clicked.connect(lambda: QDesktopServices.openUrl(QUrl(HELP_URL)))
        top_row.addWidget(help_btn)

        terms_btn = QPushButton("📜 用户协议")
        terms_btn.setToolTip("查看在线版用户协议与使用条款")
        terms_btn.clicked.connect(lambda: QDesktopServices.openUrl(QUrl(TERMS_URL)))
        top_row.addWidget(terms_btn)
        # ===============================

        layout.addLayout(top_row)

        # ===== 第2行：Cookie 提醒（无任何平台 cookie 时） =====
        self.no_cookie_frame = QFrame()
        self.no_cookie_frame.setStyleSheet("background-color: #fff3cd; border-radius: 4px; padding: 4px;")
        no_cookie_layout = QHBoxLayout(self.no_cookie_frame)
        no_cookie_layout.setContentsMargins(8, 4, 8, 4)
        self.no_cookie_label = QLabel("⚠ 您目前没有设置任何平台的 Cookie，提供 Cookie 可以获取更高的视频清晰度或下载需要登录的内容")
        self.no_cookie_label.setStyleSheet("color: #856404;")
        no_cookie_layout.addWidget(self.no_cookie_label)
        goto_cookie_btn = QPushButton("去管理 Cookie")
        goto_cookie_btn.setStyleSheet("color: #0078D4; font-weight: bold; border: none; text-decoration: underline;")
        goto_cookie_btn.setCursor(Qt.PointingHandCursor)
        goto_cookie_btn.clicked.connect(self.open_cookie_manager)
        no_cookie_layout.addWidget(goto_cookie_btn)
        no_cookie_layout.addStretch()
        layout.addWidget(self.no_cookie_frame)

        # ===== 下载目录 =====
        dir_layout = QHBoxLayout()
        dir_layout.addWidget(QLabel("下载目录:"))
        self.dir_edit = QLineEdit()
        self.dir_edit.setText(self.download_dir)
        dir_layout.addWidget(self.dir_edit)
        dir_browse_btn = QPushButton("浏览...")
        dir_browse_btn.clicked.connect(self.browse_dir)
        dir_layout.addWidget(dir_browse_btn)
        dir_open_btn = QPushButton("打开")
        dir_open_btn.clicked.connect(lambda: os.startfile(self.dir_edit.text()))
        dir_layout.addWidget(dir_open_btn)
        layout.addLayout(dir_layout)

        # ===== URL 输入框 =====
        layout.addWidget(QLabel("视频 URL（每行一条）:"))
        self.url_edit = QPlainTextEdit()
        self.url_edit.setPlaceholderText("请在此输入或粘贴视频链接，每行一条...")
        layout.addWidget(self.url_edit)

        url_btn_layout = QHBoxLayout()
        remove_btn = QPushButton("删除当前行")
        remove_btn.clicked.connect(self.remove_current_line)
        import_btn = QPushButton("从文件导入")
        import_btn.clicked.connect(self.import_urls)
        clear_btn = QPushButton("清空")
        clear_btn.clicked.connect(self.clear_urls)
        url_btn_layout.addWidget(remove_btn)
        url_btn_layout.addWidget(import_btn)
        url_btn_layout.addWidget(clear_btn)
        url_btn_layout.addStretch()
        layout.addLayout(url_btn_layout)

        # ===== 下载模式 =====
        mode_layout = QHBoxLayout()
        self.parallel_check = QCheckBox("允许并行下载（最大并发数）")
        self.parallel_check.setChecked(True)
        self.parallel_spin = QSpinBox()
        self.parallel_spin.setRange(1, 10)
        self.parallel_spin.setValue(self.max_parallel)
        self.parallel_spin.setEnabled(True)
        self.parallel_check.toggled.connect(self.parallel_spin.setEnabled)
        mode_layout.addWidget(self.parallel_check)
        mode_layout.addWidget(self.parallel_spin)
        mode_layout.addStretch()

        self.start_btn = QPushButton("▶ 开始批量下载")
        self.start_btn.clicked.connect(self.start_download)
        self.start_btn.setEnabled(self.is_current_tool_available())
        self.stop_btn = QPushButton("⏹ 停止下载")
        self.stop_btn.clicked.connect(self.stop_download)
        self.stop_btn.setEnabled(False)
        mode_layout.addWidget(self.start_btn)
        mode_layout.addWidget(self.stop_btn)
        layout.addLayout(mode_layout)

        # ===== 日志输出 =====
        log_header_layout = QHBoxLayout()
        log_header_layout.addWidget(QLabel("运行日志:"))
        log_header_layout.addStretch()
        layout.addLayout(log_header_layout)

        # 先创建 log_output
        self.log_output = QTextEdit()
        self.log_output.setReadOnly(True)
        self.log_output.setFont(QFont("Consolas", 9))
        layout.addWidget(self.log_output)

        # 再创建按钮并连接到 log_output.clear
        clear_log_btn = QPushButton("🗑 清空日志")
        clear_log_btn.clicked.connect(self.log_output.clear)
        log_header_layout.addWidget(clear_log_btn)

    # ==================== 工具相关（内置引擎优先） ====================
    def get_engine_path(self, tool_name):
        """获取引擎可执行文件路径，优先返回内置路径，否则返回 None"""
        if sys.platform == "win32":
            if tool_name == "yt-dlp":
                # 尝试多个可能的文件名
                candidates = [f"{tool_name}.exe", f"{tool_name}_arm64.exe", "yt-dlp_arm64.exe"]
            else:
                candidates = [f"{tool_name}.exe"]
        else:
            candidates = [tool_name]
        
        for exe_name in candidates:
            builtin_path = os.path.join(self.engines_dir, exe_name)
            if os.path.isfile(builtin_path) and os.access(builtin_path, os.X_OK):
                return builtin_path
        return None

    def check_tool(self, tool_name):
        """检查指定工具是否可用，返回 (是否可用, 可执行文件路径)"""
        # 1. 检查内置路径
        engine_path = self.get_engine_path(tool_name)
        if engine_path:
            # 验证一下能否运行 --version（可选，确保不是损坏文件）
            try:
                subprocess.run([engine_path, "--version"], capture_output=True, check=True)
                return True, engine_path
            except (subprocess.SubprocessError, FileNotFoundError):
                pass  # 内置文件无效，继续尝试系统 PATH
        # 2. 回退到系统 PATH
        try:
            if tool_name == "you-get":
                subprocess.run(["you-get", "--version"], capture_output=True, check=True)
                return True, "you-get"
            elif tool_name == "yt-dlp":
                subprocess.run(["yt-dlp", "--version"], capture_output=True, check=True)
                return True, "yt-dlp"
        except (subprocess.SubprocessError, FileNotFoundError):
            pass
        return False, None

    def is_current_tool_available(self):
        if self.current_tool == "you-get":
            return self.youget_available
        else:
            return self.ytdlp_available

    def update_tool_status(self):
        """更新工具栏的状态显示"""
        if self.current_tool == "you-get":
            available = self.youget_available
            tool_display = "you-get"
            engine_path = self.youget_path
        else:
            available = self.ytdlp_available
            tool_display = "yt-dlp"
            engine_path = self.ytdlp_path

        # 判断是内置还是系统
        if available:
            if engine_path and engine_path != tool_display:
                status_text = f"✅ 当前引擎: {tool_display} (内置)"
            else:
                status_text = f"✅ 当前引擎: {tool_display} (系统)"
            self.tool_status_label.setText(status_text)
            self.tool_status_label.setStyleSheet("background-color: #d4edda; color: #155724;")
        else:
            self.tool_status_label.setText(f"❌ 当前引擎: {tool_display} (不可用)")
            self.tool_status_label.setStyleSheet("background-color: #f8d7da; color: #721c24;")
            self.statusBar().showMessage(f"{tool_display} 不可用，请将引擎文件放入「{self.engines_dir}」或安装到系统 PATH", 8000)

        # 更新开始按钮的启用状态
        self.start_btn.setEnabled(available and not self.task_running)

    def on_tool_switch(self, index):
        """用户通过下拉框切换工具"""
        new_tool = self.tool_switch_combo.currentData()
        if new_tool == self.current_tool:
            return
        # 如果正在下载，禁止切换
        if self.task_running:
            QMessageBox.warning(self, "提示", "请先停止当前下载任务再切换引擎")
            self.tool_switch_combo.setCurrentIndex(0 if self.current_tool == "you-get" else 1)
            return
        self.current_tool = new_tool
        self.settings.setValue("download_tool", self.current_tool)
        self.update_tool_status()
        self.log(f"已切换下载引擎为: {self.current_tool}")

    def show_install_guide(self, tool_name):
        dlg = InstallToolDialog(tool_name, self)
        dlg.exec_()
        # 重新检测
        self.youget_available, self.youget_path = self.check_tool("you-get")
        self.ytdlp_available, self.ytdlp_path = self.check_tool("yt-dlp")
        self.update_tool_status()

    # ==================== Cookie 管理相关 ====================
    def get_cookie_for_url(self, url):
        """根据 URL 返回匹配的 cookie 文件路径，若无匹配返回 None"""
        try:
            parsed = urlparse(url)
            hostname = parsed.hostname or ""
            if not hostname:
                return None
            # 去除可能的 www. 前缀以获得更宽松匹配
            hostname_lower = hostname.lower()
            # 获取所有已保存的 cookie 域名文件
            if not os.path.exists(self.cookies_storage_dir):
                return None
            best_match = None
            best_len = 0
            for filename in os.listdir(self.cookies_storage_dir):
                if filename.endswith(".txt"):
                    domain = filename[:-4].lower()
                    # 匹配：如果 hostname 以 domain 结尾（且 domain 前为 '.' 或 完全相等）
                    # 或者 domain 是 hostname 的后缀（例如 bilibili.com 匹配 www.bilibili.com）
                    if hostname_lower == domain or hostname_lower.endswith("." + domain) or hostname_lower.endswith(domain):
                        # 选取最长匹配（更精确）
                        if len(domain) > best_len:
                            best_len = len(domain)
                            best_match = os.path.join(self.cookies_storage_dir, filename)
            return best_match
        except Exception:
            return None

    def filter_headers_for_url(self, header_text, url):
        """根据目标 URL 智能过滤自定义请求头。

        匹配规则：
        - 若请求头的值中包含 URL 或裸域名（如 https://music.163.com/ 或 music.163.com），
          则仅当目标 URL 的主机名与该域名匹配（相等或以 .域名 结尾）时才应用。
        - 若请求头的值中不含域名（如 User-Agent、Accept 等），则视为全局请求头，
          应用于所有 URL。
        """
        parsed = urlparse(url)
        hostname = (parsed.hostname or "").lower()

        result = []
        if not header_text:
            return result

        for line in header_text.splitlines():
            line = line.strip()
            if not line or ":" not in line:
                continue

            key, _, value = line.partition(":")
            value = value.strip()

            header_domain = None

            # 情形一：值是 URL，如 https://music.163.com/ 或 //music.163.com/
            url_match = re.match(r'^(?:https?:)?//([^/\s:]+)', value, re.I)
            if url_match:
                header_domain = url_match.group(1).lower()
            else:
                # 情形二：值本身就是裸域名，如 music.163.com
                if re.fullmatch(r'[a-z0-9-]+(?:\.[a-z0-9-]+)+', value, re.I):
                    header_domain = value.lower()

            if header_domain:
                # 仅在主机名匹配时才应用
                if hostname == header_domain or hostname.endswith("." + header_domain):
                    result.append(line)
                    self.log(f"请求头域名匹配 [{header_domain}] -> 注入: {line}")
                else:
                    self.log(f"请求头域名不匹配 [{header_domain}] -> 跳过: {line}")
            else:
                # 无域名，视为全局请求头
                result.append(line)

        return result

    def open_cookie_manager(self):
        dlg = PlatformCookieManager(self)
        dlg.exec_()

    def on_cookie_changed(self):
        """当 Cookie 列表变化时调用，刷新界面提醒"""
        self.update_cookie_reminder()

    def update_cookie_reminder(self):
        """更新是否有任何平台 cookie 的提醒"""
        has_cookie = False
        if os.path.exists(self.cookies_storage_dir):
            for f in os.listdir(self.cookies_storage_dir):
                if f.endswith(".txt"):
                    has_cookie = True
                    break
        self.no_cookie_frame.setVisible(not has_cookie)

    # ==================== 设置相关 ====================
    def on_settings_changed(self):
        """设置对话框保存后调用"""
        self.log_dir = self.settings.value("log_dir", "")
        # 重新读取工具选择
        new_tool = self.settings.value("download_tool", "you-get")
        if new_tool != self.current_tool:
            self.current_tool = new_tool
            # 更新下拉框选项
            idx = self.tool_switch_combo.findData(new_tool)
            if idx >= 0:
                self.tool_switch_combo.setCurrentIndex(idx)
            self.update_tool_status()
        self.update_cookie_reminder()

    # ==================== 基础功能 ====================
    def browse_dir(self):
        path = QFileDialog.getExistingDirectory(self, "选择下载目录")
        if path:
            self.dir_edit.setText(path)
            self.settings.setValue("download_dir", path)

    def remove_current_line(self):
        cursor = self.url_edit.textCursor()
        block = cursor.block()
        start = block.position()
        end = start + block.length()
        cursor.setPosition(start)
        cursor.setPosition(end, QTextCursor.KeepAnchor)
        cursor.removeSelectedText()
        self.url_edit.setTextCursor(cursor)

    def import_urls(self):
        path, _ = QFileDialog.getOpenFileName(self, "导入 URL 列表", "", "文本文件 (*.txt);;所有文件 (*)")
        if path:
            with open(path, 'r', encoding='utf-8') as f:
                urls = f.read()
            self.url_edit.insertPlainText(urls)
            self.log(f"已从 {path} 导入 URL")

    def clear_urls(self):
        self.url_edit.clear()

    def open_settings(self):
        dlg = SettingsDialog(self)
        dlg.exec_()

    def log(self, msg):
        self.log_signal.emit(msg)

    def append_log(self, msg):
        now = datetime.now().strftime("%H:%M:%S")
        line = f"[{now}] {msg}"
        self.log_output.append(line)
        cursor = self.log_output.textCursor()
        cursor.movePosition(QTextCursor.End)
        self.log_output.setTextCursor(cursor)

        if hasattr(self, 'log_dir') and self.log_dir:
            try:
                # === 新增：按日期创建子目录 ===
                date_str = datetime.now().strftime("%Y%m%d")
                daily_log_dir = os.path.join(self.log_dir, date_str)
                os.makedirs(daily_log_dir, exist_ok=True)
                log_path = os.path.join(daily_log_dir, "download.log")
                # =================================
                with open(log_path, 'a', encoding='utf-8') as f:
                    f.write(line + "\n")
            except Exception as e:
                print(f"写入日志文件失败: {e}")

    # ==================== 下载控制 ====================
    def stop_download(self):
        self.stop_flag = True
        for proc in self.processes:
            if proc.state() != QProcess.NotRunning:
                proc.kill()
        self.url_queue.clear()
        self.processes.clear()
        self.task_running = False
        self.start_btn.setEnabled(self.is_current_tool_available())
        self.stop_btn.setEnabled(False)
        self.log("用户停止了下载任务。")

    def start_download(self):
        if not self.is_current_tool_available():
            QMessageBox.warning(self, "缺少下载引擎", f"请先安装 {self.current_tool} 后再下载！\n点击「设置」查看安装帮助。")
            return

        out_dir = self.dir_edit.text().strip()
        if not out_dir or not os.path.isdir(out_dir):
            QMessageBox.warning(self, "警告", "下载目录无效，请重新选择。")
            return

        raw_text = self.url_edit.toPlainText()
        urls = []
        for line in raw_text.splitlines():
            line = line.strip()
            if line and line not in urls:
                urls.append(line)

        if not urls:
            QMessageBox.warning(self, "警告", "URL 列表为空，请添加下载链接。")
            return

        self.url_queue = urls[:]
        self.total_tasks = len(urls)
        self.success_count = 0
        self.fail_count = 0
        self.stop_flag = False
        self.max_parallel = self.parallel_spin.value() if self.parallel_check.isChecked() else 1

        self.log(f"开始批量下载，共 {self.total_tasks} 个任务，最大并行数 {self.max_parallel}")
        self.log(f"下载目录: {out_dir}")
        self.log(f"使用下载引擎: {self.current_tool}")

        self.start_btn.setEnabled(False)
        self.stop_btn.setEnabled(True)
        self.task_running = True
        self.processes = []
        self.successful_files = []  # 记录成功下载文件的完整路径

        for _ in range(min(self.max_parallel, len(self.url_queue))):
            self.start_next_process()

    def start_next_process(self):
        if self.stop_flag or not self.url_queue:
            if not self.url_queue and not self.processes:
                self.finish_download()
            return

        url = self.url_queue.pop(0)
        out_dir = self.dir_edit.text().strip()

        # 获取该 URL 对应的 cookie 文件
        cookie_file = self.get_cookie_for_url(url)
        if cookie_file:
            self.log(f"为 {url} 匹配到 Cookie: {os.path.basename(cookie_file)}")
        else:
            self.log(f"未找到匹配的 Cookie，将不使用 Cookie 下载: {url}")

        proc = QProcess(self)
        proc.setProcessChannelMode(QProcess.MergedChannels)

        # 获取当前工具的可执行文件路径
        if self.current_tool == "you-get":
            executable = self.youget_path
        else:
            executable = self.ytdlp_path
        if not executable:
            self.log(f"错误: 无法找到 {self.current_tool} 引擎")
            self.fail_count += 1
            self.start_next_process()
            return

        # ===== 智能匹配自定义请求头 =====
        custom_headers_text = self.settings.value("custom_headers", "").strip()
        header_args = []
        if custom_headers_text:
            matched_lines = self.filter_headers_for_url(custom_headers_text, url)
            for line in matched_lines:
                if self.current_tool == "yt-dlp":
                    header_args.extend(["--add-header", line])
                elif self.current_tool == "you-get":
                    header_args.extend(["-H", line])
            if header_args:
                self.log(f"已为当前任务注入 {len(header_args) // 2} 条自定义请求头")
            else:
                self.log("当前任务无匹配的自定义请求头")

        # 构建参数
        if self.current_tool == "you-get":
            args = []
            if cookie_file and os.path.isfile(cookie_file):
                args += ["--cookie", cookie_file]
            
            args += header_args
            
            args += ["-o", out_dir, url]
        else:  # yt-dlp
            args = []
            if cookie_file and os.path.isfile(cookie_file):
                args += ["--cookies", cookie_file]
            
            args += header_args

            args += ["--print", "after_move:filepath"]
            
            args += ["-P", out_dir, url]

        proc.finished.connect(lambda exit_code, exit_status, p=proc: self.on_process_finished(p, exit_code, exit_status))
        proc.readyReadStandardOutput.connect(lambda p=proc: self.read_output(p))

        self.processes.append(proc)
        self.log(f"启动下载 [{self.current_tool}]: {url}")
        proc.start(executable, args)

    def read_output(self, proc):
        data = proc.readAllStandardOutput()
        if data:
            text = data.data().decode(errors='replace').strip()
            if text:
                self.log(f"[输出] {text}")
                
                if self.current_tool == "yt-dlp":
                    for line in text.splitlines():
                        line = line.strip()
                        if (":" in line and ("\\" in line or "/" in line)) or (line.startswith("/")):
                            if not os.path.isabs(line):
                                line = os.path.join(self.dir_edit.text().strip(), line)
                            if line not in self.successful_files:
                                self.successful_files.append(line)
                                self.log(f"检测到文件路径: {line}")
                # ==========================================

    def on_process_finished(self, proc, exit_code, exit_status):
        # 获取 URL（命令参数的最后一个）
        args = proc.arguments()
        url = args[-1] if args else "未知"
        if exit_status == QProcess.NormalExit and exit_code == 0:
            self.success_count += 1
            self.log(f"✔ 下载成功: {url}")
        else:
            self.fail_count += 1
            err_output = proc.readAllStandardOutput().data().decode(errors='replace')
            reason = "未知错误"
            if "cookie" in err_output.lower():
                reason = "Cookie 文件错误或已过期"
            elif "404" in err_output:
                reason = "视频不存在 (404)"
            elif "403" in err_output:
                reason = "访问被拒绝 (403)，可能需要有效的 Cookie"
            elif "timeout" in err_output.lower():
                reason = "连接超时"
            elif "unsupported" in err_output.lower():
                reason = "不支持的网站或格式"
            else:
                lines = err_output.splitlines()
                if lines:
                    reason = lines[-1][:80]
            self.log(f"✘ 下载失败: {url} 原因: {reason}")

        if proc in self.processes:
            self.processes.remove(proc)
        proc.deleteLater()

        if not self.stop_flag and self.url_queue:
            self.start_next_process()
        elif not self.processes:
            self.finish_download()

    def finish_download(self):
        self.task_running = False
        self.start_btn.setEnabled(self.is_current_tool_available())
        self.stop_btn.setEnabled(False)

        # === 需求五：分行显示下载文件的完整目录+文件名 ===
        summary_lines = [f"下载完毕！成功: {self.success_count}，失败: {self.fail_count}，总计: {self.total_tasks}"]
        if hasattr(self, 'successful_files') and self.successful_files:
            summary_lines.append("成功下载的文件:")
            summary_lines.extend(self.successful_files)
        else:
            summary_lines.append(f"下载目录: {self.dir_edit.text().strip()}")
        
        summary = "\n".join(summary_lines)
        self.log(summary)

        # === 需求四：弹窗增加打开功能 ===
        msg_box = QMessageBox(self)
        msg_box.setWindowTitle("批量下载完成")
        msg_box.setText(f"下载完毕！成功: {self.success_count}，失败: {self.fail_count}，总计: {self.total_tasks}")
        
        if hasattr(self, 'successful_files') and self.successful_files:
            msg_box.setDetailedText("成功文件:\n" + "\n".join(self.successful_files))
        
        open_btn = msg_box.addButton("打开下载目录", QMessageBox.ActionRole)
        ok_btn = msg_box.addButton("OK", QMessageBox.AcceptRole)
        msg_box.exec_()
        
        if msg_box.clickedButton() == open_btn:
            try:
                os.startfile(self.dir_edit.text().strip())
            except Exception as e:
                QMessageBox.warning(self, "错误", f"无法打开下载目录：{e}")


# ============================================================
# 入口
# ============================================================
if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setStyle("Fusion")

    # ===== 启动前检查用户协议 =====
    settings = QSettings("YouGetBatchTool", "Settings")
    skip_agreement = settings.value("agreement_skip", False, type=bool)

    if not skip_agreement:
        dlg = AgreementDialog()
        result = dlg.exec_()
        if result != QDialog.Accepted or not dlg.agreed:
            sys.exit(0)
        if dlg.no_ask_again:
            settings.setValue("agreement_skip", True)
    # ================================

    window = YouGetBatchDownloader()
    window.show()
    sys.exit(app.exec_())
